// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package query

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type JobState string

const (
	JobStatePending      JobState = "pending"
	JobStateRunning      JobState = "running"
	JobStateSuspended    JobState = "suspended"
	JobStatePendingRetry JobState = "pending_retry"
	JobStateCompleted    JobState = "completed"
	JobStateFailed       JobState = "failed"
)

func (e *JobState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = JobState(s)
	case string:
		*e = JobState(s)
	default:
		return fmt.Errorf("unsupported scan type for JobState: %T", src)
	}
	return nil
}

type NullJobState struct {
	JobState JobState
	Valid    bool // Valid is true if JobState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullJobState) Scan(value interface{}) error {
	if value == nil {
		ns.JobState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.JobState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullJobState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.JobState), nil
}

type Job struct {
	ID                string
	DefinitionName    string
	DefinitionVersion string
	State             JobState
	Env               []byte
	Params            []byte
	ResultExitCode    pgtype.Int4
	ResultOutput      []byte
	Error             sql.NullString
	CreatedAt         time.Time
	StartedAt         sql.NullTime
	CompletedAt       sql.NullTime
	CheckpointCount   int32
	LastCheckpointAt  sql.NullTime
	RetryCount        int32
	ResumeAt          sql.NullTime
	CheckpointPath    sql.NullString
	RuntimeType       string
	RuntimeConfig     []byte
	Metadata          []byte
}

type JobDefinition struct {
	Name        string
	Version     string
	RuntimeType string
	Config      []byte
	RetryPolicy []byte
	Metadata    []byte
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
