#!/bin/bash
# Build a Firecracker-compatible ext4 rootfs from a Dockerfile.
#
# Usage: build-fc-rootfs.sh <dockerfile_path> <output_rootfs_path> [network_config]
#
# Arguments:
#   dockerfile_path   - Path to the Dockerfile (e.g., demo/Dockerfile.checkpoint_restore)
#   output_rootfs     - Where to write the ext4 rootfs (e.g., /tmp/rootfs.ext4)
#   network_config    - Optional: "guest_ip,gateway" (e.g., "172.16.0.2/24,172.16.0.1")
#                       If provided, the init script will configure networking.
#
# Dependencies: buildah, skopeo, umoci, e2fsprogs (mkfs.ext4), jq
#
# Example:
#   ./scripts/build-fc-rootfs.sh demo/Dockerfile.checkpoint_restore /tmp/test.ext4
#   ./scripts/build-fc-rootfs.sh demo/Dockerfile.checkpoint_restore /tmp/test.ext4 "172.16.0.2/24,172.16.0.1"

set -euo pipefail

die() { echo "error: $1" >&2; exit 1; }

DOCKERFILE="${1:-}"
OUTPUT="${2:-}"
NETWORK_CONFIG="${3:-}"

[[ -z "$DOCKERFILE" || -z "$OUTPUT" ]] && die "usage: $0 <dockerfile_path> <output_rootfs_path> [network_config]"
[[ ! -f "$DOCKERFILE" ]] && die "Dockerfile not found: $DOCKERFILE"

# Check dependencies
for cmd in buildah skopeo umoci mkfs.ext4 jq; do
    command -v "$cmd" &>/dev/null || die "$cmd not found. Install with: apt-get install buildah skopeo umoci e2fsprogs jq"
done

# Parse network config if provided
GUEST_IP=""
GATEWAY=""
if [[ -n "$NETWORK_CONFIG" ]]; then
    GUEST_IP=$(echo "$NETWORK_CONFIG" | cut -d',' -f1)
    GATEWAY=$(echo "$NETWORK_CONFIG" | cut -d',' -f2)
    [[ -z "$GUEST_IP" || -z "$GATEWAY" ]] && die "Invalid network config. Expected format: 'guest_ip,gateway' (e.g., '172.16.0.2/24,172.16.0.1')"
    echo "Network config: guest_ip=$GUEST_IP, gateway=$GATEWAY"
fi

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"; buildah rm $(buildah containers -q 2>/dev/null) &>/dev/null || true' EXIT

DOCKERFILE_DIR=$(dirname "$DOCKERFILE")
DOCKERFILE_NAME=$(basename "$DOCKERFILE")
IMG="fc-rootfs-$$"

echo "Building Docker image from $DOCKERFILE..."
buildah bud -t "$IMG" -f "$DOCKERFILE_NAME" "$DOCKERFILE_DIR" >/dev/null 2>&1

# Export to OCI layout and extract config
echo "Exporting image to OCI layout..."
skopeo copy "containers-storage:localhost/$IMG" "oci:$WORK/oci:latest" >/dev/null

CONFIG=$(skopeo inspect --config "oci:$WORK/oci:latest")
WORKDIR=$(echo "$CONFIG" | jq -r '.config.WorkingDir // "/"')
ENTRYPOINT=$(echo "$CONFIG" | jq -r '(.config.Entrypoint // []) | map(@sh) | join(" ")')
CMD=$(echo "$CONFIG" | jq -r '(.config.Cmd // []) | map(@sh) | join(" ")')
ENV_VARS=$(echo "$CONFIG" | jq -r '(.config.Env // []) | .[] | split("=") | "export \(.[0])=\"\(.[1:] | join("="))\"" ')

echo "  WorkDir: $WORKDIR"
echo "  Entrypoint: $ENTRYPOINT"
echo "  Cmd: $CMD"

# Unpack to rootfs
echo "Unpacking image..."
umoci unpack --image "$WORK/oci:latest" "$WORK/bundle" >/dev/null
FS="$WORK/bundle/rootfs"

# Prepare for Firecracker
mkdir -p "$FS"/{dev,proc,sys,run,tmp}
[[ ! -s "$FS/etc/resolv.conf" ]] && printf "nameserver 8.8.8.8\n" > "$FS/etc/resolv.conf"

# Generate network setup commands
NETWORK_SETUP=""
if [[ -n "$GUEST_IP" && -n "$GATEWAY" ]]; then
    NETWORK_SETUP=$(cat <<NETEOF
# Configure networking
if ip link show eth0 &>/dev/null; then
    ip link set eth0 up
    ip addr add $GUEST_IP dev eth0
    ip route add default via $GATEWAY
    echo "nameserver 8.8.8.8" > /etc/resolv.conf
    echo "Network configured: $GUEST_IP via $GATEWAY"
fi
NETEOF
)
fi

# Generate init from image's ENTRYPOINT/CMD
echo "Creating /init script..."
cat > "$FS/init" <<EOF
#!/bin/sh
# Firecracker init script - generated by build-fc-rootfs.sh
# Sets up the VM environment and runs the container's entrypoint

# Mount essential filesystems
mount -t proc proc /proc
mount -t sysfs sys /sys
mount -t devtmpfs dev /dev 2>/dev/null || true

# Set up PATH
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

# Seed random if hardware RNG is available
[ -c /dev/hwrng ] && dd if=/dev/hwrng of=/dev/urandom bs=512 count=4 2>/dev/null

$NETWORK_SETUP

# Set environment variables from container config
$ENV_VARS

# Source runtime-injected environment variables (CHECKER_API_URL, CHECKER_JOB_ID, etc.)
# These are written by the Firecracker runtime before starting the VM.
[ -f /etc/checker.env ] && . /etc/checker.env

# Change to working directory
cd $WORKDIR

# Run the container's entrypoint
$ENTRYPOINT $CMD
EXIT_CODE=\$?

# Shutdown the VM
reboot -f
EOF
chmod +x "$FS/init"

# Create ext4 filesystem
echo "Creating ext4 filesystem..."
SIZE_MB=$(( $(du -sm "$FS" | cut -f1) * 2 ))
[[ $SIZE_MB -lt 64 ]] && SIZE_MB=64
echo "  Size: ${SIZE_MB}MB"

truncate -s "${SIZE_MB}M" "$OUTPUT"
mkfs.ext4 -F -L rootfs -O ^metadata_csum,^64bit -d "$FS" "$OUTPUT" >/dev/null

# Optimize filesystem
e2fsck -fy "$OUTPUT" &>/dev/null || true
resize2fs -M "$OUTPUT" &>/dev/null || true

# Cleanup image
buildah rmi "$IMG" &>/dev/null || true

FINAL_SIZE=$(du -h "$OUTPUT" | cut -f1)
echo "Rootfs created: $OUTPUT ($FINAL_SIZE)"
